### ISSUE TITLE
Make it easy to run the weekly payout script

### ISSUE THREAD

**Issue by josojo** [bh2smith/cow-solver-rewards#14]
Currently the topup script has some goodies. Eg. it will directly link to the safe payout tool and leaves little error for the user.

```

Topups required for staging-zeroex, prod-quasimodo, prod-oneinch, prod-zeroex, prod-cowdexag solver(s). Use the following CSV file at:
  https://gnosis-safe.io/app/eth:0x6C642caFCbd9d8383250bb25F67aE409147f78b2/apps?appUrl=https://cloudflare-ipfs.com/ipfs/Qme49gESuwpSvwANmEqo34yfCkzyQehooJ5yL7aHmKJnpZ/
Total Funds needed: 72.57113335376707
###
token_type,token_address,receiver,amount,id
native,,0xDe786877a10DBb7EBa25a4DA65aEcf47654F08ab,2.728468993448503064,
native,,0x77ec2A722c2393D3fD64617BBaF1499C713e616b,8.584310745748181454,
native,,0xdE1c59Bc25D806aD9DdCbe246c4B5e5505645718,24.060989955841389161,
native,,0xe92F359e6F05564849AFa933CE8F62b8007A1d5D,26.019121278358327370,
native,,0x2d15894fac906386ff7f4bd07fceac43fcf80c73,11.178242380370669270,
```
We should have something similar.

**Comment by bh2smith** [comment]
The file is already written to the out directory... eventually I would imagine the script would send the transaction directly to the safe  from the proposer account. I don't see any need or reason to upload to IPFS and run another service. Everything can be entirely contained in whatever docket image we publish from here.

**Comment by josojo** [comment]
> eventually I would imagine the script would send the transaction directly to the safe from the proposer account.
I don't like it, as this means that we have to have the PK of the proposer somewhere in our console. I prefer to have it in metamask

**Comment by bh2smith** [comment]
The private key of the proposer would be in the project secrets.
