### ISSUE TITLE
Generate a Solver Reimbursement Receipt

### ISSUE THREAD

**Issue by nlordell** [bh2smith/cow-solver-rewards#34]
Similar to the one for the COW token allocation. This is something that we can keep a record of and makes it easier to "prove" to each solver why they got what amount.

**Comment by bh2smith** [comment]
One thing we might be able to do to make this deterministic is to use the clearing prices from settlement call data to evaluate imbalances. There were some cases where we didn't have this information but @josojo knows more details on that.

**Comment by josojo** [comment]
I think the receipt could also be a table of the token imbalances + another table of the prices used. 
Then at least one part of the receipt is reproducable and the other one is just documented.

Yes, Ben i agree that the clearing prices are not always there and hence, we can not use them easily.

**Comment by josojo** [comment]
Yes exactly. If a settlement has the token GNO, DAI, but it was trading through an AMM GNO-ETH and there was slippage in ETH, there is no eth prices from the clearing prices to evaluate the slipapge.
