### ISSUE TITLE
future-proof realized_fees

### ISSUE THREAD

**Issue by josojo** [bh2smith/cow-solver-rewards#8]
Currently, we have a query
```
realized_fees as (
    select
        concat(
            to_char('{{StartTime}}'::timestamptz, 'YYYY-MM-DD'),
            ' to ',
            to_char('{{EndTime}}'::timestamptz - interval '1 day', 'YYYY-MM-DD')
        ) as accounting_period,
        sum(atoms_bought) / 10^18 as realized_fees_eth
    from gnosis_protocol_v2."trades"
    where trader in (
        select address
        from gnosis_protocol_v2."view_solvers"
        where name = 'Withdraw'
    )
    and block_time >= '{{StartTime}}'
    and block_time < '{{EndTime}}'
)
```
This has the hidden assumption that withdraw accounts only trade against weth, i.e. "atoms_bought" are WETH. 
In order to make the query future-proof for accidental other trades, we might wanna add a where statement that checks that the tokens bought are either weth or ETH.

**Comment by bh2smith** [comment]
Actually this query already covers that case as you will notice there is nothing specific to the token being purchased.

**Comment by bh2smith** [comment]
I believe we decided this was not necessary since realized fees are not evaluated as part of the reimbursement (but merely for informational purposes).
